### ISSUE TITLE
alpha / beta version

### ISSUE THREAD

**Issue by themakunga** [workhorsy/nulldc-linux#1]
Hi! I'm big fan of sega dreamcast and I wanna know if there's gonna be an alpha or beta version soon, to test and help with the issues

regards!

**Comment by workhorsy** [comment]
Hi kojimairiguchi. This was just something I did for fun in 2013. It kind of fizzled out when I realized much of Nulldc is written in DirectX shaders (Windows only), and would have to be ported to OpenGL shaders. However I don't know enough about shaders to do that. Plus I'm supper busy with work now.

I would recommend looking into Reicast https://github.com/reicast/reicast-emulator, since it apparently already works on Linux. Plus I'm pretty sure Reicast uses parts of NullDC.

**Comment by workhorsy** [comment]
I'll update the readme to have the current project status.
